---
engines:
  # Disable TSQLLint - it's for T-SQL (SQL Server), not PostgreSQL
  tsqllint:
    enabled: false
    exclude_paths:
      - "**/*.sql"
  TSQLLint:
    enabled: false
    exclude_paths:
      - "**/*.sql"
